"""FastAPI control plane for SolanaTrader.

Serves:
  - /health                      basic liveness
  - /dashboard                   HTML main view
  - /ops                         HTML ops view
  - /analytics                   HTML analytics view
  - /opportunity/{id}            HTML per-opp detail
  - /metrics                     JSON metrics snapshot
  - /opportunities               JSON recent opportunities
  - /opportunities/{id}/full     JSON with all pipeline stages
  - /pnl                         JSON summary
  - /pnl/analytics               JSON per-pair / per-venue / hourly
  - /scan-history                JSON scan rows
  - /funnel                      JSON status counts
  - /wallet/balance              JSON SOL balance (via Alchemy RPC)
  - /execution                   GET/POST execution kill-switch state

Auth: HTTP Basic (``DASHBOARD_USER`` / ``DASHBOARD_PASS`` from ``.env``).
The dashboards themselves are HTML pages generated by the modules in
``src/dashboards/``.
"""

from __future__ import annotations

import logging
import os
import secrets
from pathlib import Path
from typing import Any

from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.responses import HTMLResponse, JSONResponse, RedirectResponse
from fastapi.security import HTTPBasic, HTTPBasicCredentials

from control_state import get_control
from observability.metrics import MetricsCollector
from observability.wallet import get_wallet_balances
from persistence.db import DbConnection, get_db, init_db
from persistence.repository import Repository
from risk.policy import RiskPolicy

logger = logging.getLogger(__name__)

_security = HTTPBasic()
_metrics_ref: MetricsCollector | None = None
_scanner_ref: Any = None       # optional injected scanner (for pause/resume hooks)

_PROJECT_ROOT = Path(__file__).resolve().parents[2]
_KILL_SWITCH_PATH = _PROJECT_ROOT / "data" / ".execution_kill_switch"


def set_metrics_ref(metrics: MetricsCollector) -> None:
    """Inject the metrics collector used by run_event_driven into the API."""
    global _metrics_ref
    _metrics_ref = metrics


def set_scanner_ref(scanner: Any) -> None:
    global _scanner_ref
    _scanner_ref = scanner


# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------

def create_app(
    repo: Repository | None = None,
    risk_policy: RiskPolicy | None = None,
) -> FastAPI:
    app = FastAPI(title="SolanaTrader", version="0.1")

    # Inject / lazily resolve repo
    def _repo() -> Repository:
        nonlocal repo
        if repo is None:
            conn: DbConnection = get_db() if get_db() else init_db()
            repo = Repository(conn)
        return repo

    policy = risk_policy or RiskPolicy()

    # --- Auth ---
    def _verify(credentials: HTTPBasicCredentials = Depends(_security)) -> str:
        user_ok = secrets.compare_digest(
            credentials.username,
            os.environ.get("DASHBOARD_USER", "admin"),
        )
        pass_ok = secrets.compare_digest(
            credentials.password,
            os.environ.get("DASHBOARD_PASS", "adminTest"),
        )
        if not (user_ok and pass_ok):
            raise HTTPException(
                status_code=status.HTTP_401_UNAUTHORIZED,
                detail="Invalid credentials",
                headers={"WWW-Authenticate": "Basic"},
            )
        return credentials.username

    # ------------------------------------------------------------------
    # Liveness
    # ------------------------------------------------------------------

    @app.get("/health")
    def health() -> dict:
        return {"status": "ok", "service": "solana-trader"}

    # ------------------------------------------------------------------
    # HTML dashboards (lazy import to avoid circular deps)
    # ------------------------------------------------------------------

    @app.get("/", response_class=HTMLResponse)
    @app.get("/dashboard", response_class=HTMLResponse)
    def dashboard(request: Request, user: str = Depends(_verify)) -> str:
        from dashboards.main_dashboard import render
        return render(_repo(), _metrics_ref, filters=dict(request.query_params))

    @app.get("/ops", response_class=HTMLResponse)
    def ops(request: Request, user: str = Depends(_verify)) -> str:
        from dashboards.ops_dashboard import render
        return render(_repo(), _metrics_ref, policy,
                      filters=dict(request.query_params))

    @app.get("/analytics", response_class=HTMLResponse)
    def analytics(request: Request, user: str = Depends(_verify)) -> str:
        from dashboards.analytics_dashboard import render
        return render(_repo(), filters=dict(request.query_params))

    @app.get("/opportunity/{opp_id}", response_class=HTMLResponse)
    def opportunity(opp_id: str, user: str = Depends(_verify)) -> str:
        from dashboards.opportunity_detail import render
        return render(_repo(), opp_id)

    # ------------------------------------------------------------------
    # JSON endpoints
    # ------------------------------------------------------------------

    @app.get("/metrics")
    def metrics(user: str = Depends(_verify)) -> dict:
        return _metrics_ref.snapshot() if _metrics_ref else {}

    @app.get("/opportunities")
    def opportunities(limit: int = 50, user: str = Depends(_verify)) -> list[dict]:
        return _repo().get_recent_opportunities(limit=limit)

    @app.get("/opportunities/{opp_id}/full")
    def opportunity_full(opp_id: str, user: str = Depends(_verify)) -> dict:
        r = _repo()
        opp = r.get_opportunity(opp_id)
        if opp is None:
            raise HTTPException(404, "opportunity not found")
        return {
            "opportunity": opp,
            "pricing": r.get_pricing(opp_id),
            "risk": r.get_risk_decision(opp_id),
            "simulation": r.get_simulation(opp_id),
            "execution": r.get_latest_execution_attempt(opp_id),
        }

    @app.get("/pnl")
    def pnl(user: str = Depends(_verify)) -> dict:
        return _repo().get_pnl_summary()

    @app.get("/pnl/analytics")
    def pnl_analytics(
        since: str | None = None,
        until: str | None = None,
        user: str = Depends(_verify),
    ) -> dict:
        return _repo().get_pnl_analytics(since=since, until=until)

    @app.get("/scan-history")
    def scan_history(
        pair: str | None = None,
        reason: str | None = None,
        limit: int = 200,
        user: str = Depends(_verify),
    ) -> list[dict]:
        return _repo().get_scan_history(pair=pair, reason=reason, limit=limit)

    @app.get("/funnel")
    def funnel(user: str = Depends(_verify)) -> dict:
        return _repo().get_opportunity_funnel()

    @app.get("/windows")
    def windows(user: str = Depends(_verify)) -> dict:
        """Return stats for every predefined time window (5m, 15m, 1h, ..., 1m).

        Shape:
            {
              "5m":  {"opportunities": {...}, "trades": {...}, "profit": {...}},
              "15m": {...},
              ...
            }

        Backed by observability.time_windows.get_all_windows.
        """
        from observability.time_windows import get_all_windows
        return get_all_windows(_repo().conn)

    @app.get("/windows/{window_key}")
    def window_single(window_key: str, user: str = Depends(_verify)) -> dict:
        """Return stats for a single window key. Invalid keys get {'error': ...}."""
        from observability.time_windows import get_windowed_stats
        return get_windowed_stats(_repo().conn, window_key)

    @app.get("/wallet/balance")
    def wallet_balance(user: str = Depends(_verify)) -> dict:
        return get_wallet_balances()

    # ------------------------------------------------------------------
    # Execution kill-switch controls
    # ------------------------------------------------------------------

    @app.get("/execution")
    def execution_status(user: str = Depends(_verify)) -> dict:
        enabled_env = os.environ.get("SOLANA_EXECUTION_ENABLED", "").lower() in ("true", "1", "yes")
        return {
            "execution_enabled_env": enabled_env,
            "kill_switch_active": _KILL_SWITCH_PATH.exists(),
            "risk_policy": policy.to_dict(),
        }

    @app.post("/execution/kill")
    def execution_kill(user: str = Depends(_verify)) -> dict:
        _KILL_SWITCH_PATH.parent.mkdir(parents=True, exist_ok=True)
        _KILL_SWITCH_PATH.touch()
        logger.warning("[api] KILL SWITCH ACTIVATED by %s", user)
        return {"kill_switch_active": True}

    @app.post("/execution/resume")
    def execution_resume(user: str = Depends(_verify)) -> dict:
        if _KILL_SWITCH_PATH.exists():
            _KILL_SWITCH_PATH.unlink()
            logger.warning("[api] kill switch CLEARED by %s", user)
        return {"kill_switch_active": False}

    @app.get("/risk/policy")
    def risk_policy_view(user: str = Depends(_verify)) -> dict:
        return policy.to_dict()

    # ------------------------------------------------------------------
    # Scanner runtime controls (pause, pair + venue toggles)
    # ------------------------------------------------------------------

    @app.get("/scanner")
    def scanner_status(user: str = Depends(_verify)) -> dict:
        return get_control().snapshot()

    @app.post("/scanner/pause")
    def scanner_pause(user: str = Depends(_verify)) -> dict:
        get_control().paused = True
        logger.warning("[api] scanner PAUSED by %s", user)
        return get_control().snapshot()

    @app.post("/scanner/resume")
    def scanner_resume(user: str = Depends(_verify)) -> dict:
        get_control().paused = False
        logger.warning("[api] scanner RESUMED by %s", user)
        return get_control().snapshot()

    @app.post("/pairs/{pair:path}/disable")
    def pair_disable(pair: str, user: str = Depends(_verify)) -> dict:
        get_control().disabled_pairs.add(pair)
        logger.warning("[api] pair DISABLED: %s (by %s)", pair, user)
        return get_control().snapshot()

    @app.post("/pairs/{pair:path}/enable")
    def pair_enable(pair: str, user: str = Depends(_verify)) -> dict:
        get_control().disabled_pairs.discard(pair)
        logger.warning("[api] pair enabled: %s (by %s)", pair, user)
        return get_control().snapshot()

    @app.post("/venues/{venue:path}/disable")
    def venue_disable(venue: str, user: str = Depends(_verify)) -> dict:
        get_control().disabled_venues.add(venue)
        logger.warning("[api] venue DISABLED: %s (by %s)", venue, user)
        return get_control().snapshot()

    @app.post("/venues/{venue:path}/enable")
    def venue_enable(venue: str, user: str = Depends(_verify)) -> dict:
        get_control().disabled_venues.discard(venue)
        logger.warning("[api] venue enabled: %s (by %s)", venue, user)
        return get_control().snapshot()

    return app
